services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    environment:
      PORT: 4000
      FRONTEND_URL: http://localhost:5173
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/sms_platform?schema=public
      REDIS_URL: redis://redis:6379
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      DEFAULT_FROM_NUMBER: ${DEFAULT_FROM_NUMBER}
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"

  worker:
    build:
      context: ./backend
    command: ["node", "src/jobs/bulkSms.worker.js"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/sms_platform?schema=public
      REDIS_URL: redis://redis:6379
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      DEFAULT_FROM_NUMBER: ${DEFAULT_FROM_NUMBER}
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_SOCKET_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  pgdata:
